import os, datetime, time, discord, sys
from discord.ext import commands
from modules import util

async def setup(bot: commands.Bot):
    await bot.add_cog(Crash(bot))

class Crash(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.client = bot
    @commands.command()
    async def crash(self, ctx):
        for _ in range(15):
            await ctx.send(':grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face: ﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽:grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses:')
            await ctx.send(""":chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains:""")
            await ctx.send(':grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face: ﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽:grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses:')
            await ctx.send(""":chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains:""")
            await ctx.send(':grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::triumph::jack_o_lantern::cold_face: ﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽:grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses::grinning::thumbsup::eyes::heart::watermelon::fork_and_knife::tired_face::poop::weary::yum::nerd::sunglasses:')
            await ctx.send(""":chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains::chains:""")
                
        
    